# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:15-alpine
    container_name: auth-postgres
    restart: always
    environment:
      - POSTGRES_USER=auth
      - POSTGRES_PASSWORD=auth-pwd
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql-scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
